variable "project_name" {
  description = "Short name used to prefix all resource names"
  type        = string
}

variable "environment" {
  description = "Deployment environment"
  type        = string
  validation {
    condition     = contains(["dev", "prod"], var.environment)
    error_message = "environment must be 'dev' or 'prod'."
  }
}

variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
}

variable "owner" {
  description = "Owner tag applied to all resources"
  type        = string
}

# -- Grafana Cloud cross-account access --------------------------------------
# Both values come from the Grafana Cloud console, not from us: start the
# "Connect AWS account" flow at grafana.com under your stack's Connections ->
# Amazon CloudWatch integration. Grafana displays its own AWS account ID and
# generates an ExternalId unique to your org at that point - do not guess or
# reuse either value from documentation examples, they are tenant-specific.

variable "grafana_aws_account_id" {
  description = "AWS account ID Grafana Cloud uses to assume this role (shown in the Grafana Cloud Connect AWS account flow)"
  type        = string
}

variable "grafana_external_id" {
  description = "ExternalId generated by Grafana Cloud for this org, required by the assume-role trust condition"
  type        = string
}
